version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: ngBank
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    image: ngbank-backend
    depends_on:
      - db
    ports:
    - '3333:3333'